### ISSUE TITLE
SQL Configuration

### ISSUE THREAD

**Issue by muehre** [hammy2899/ArchonCrates#29]
I am missing a config for the SQL connection.
Would be awesome to have MySQL support to use this on a multiserver setup instead of sqllite only
https://github.com/hammy2899/ArchonCrates/blob/f1150a4c334dd912dc1b15a266bb61064fa77ea2/src/com/HamiStudios/ArchonCrates/API/Libs/DatabaseHandler.java#L28

Greetings

**Comment by y0hami** [comment]
I did have plans to add MySQL support but as you can probably see I haven't been so active with ArchonCrates in a while because I have had a lot going on.

I have been thinking about what I am going to do with the project and I came to the decision to make an update which will add/fix all the current issues on the repo. When I get the time and release this update I am going to call that the final update to ArchonCrates for new features etc. after that it will only be security and Minecraft compatibility updates.

**Comment by muehre** [comment]
If you are up for it, i will open a PR ;)

**Comment by y0hami** [comment]
You are more than welcome to open a PR 😃

**Comment by y0hami** [comment]
End of Life Statement
Please read the following statement: [EOL_STATEMENT.md](https://github.com/hammy2899/ArchonCrates/blob/4125fbfc764db261f7fad6301b5aa66dc04ff131/EOL_STATEMENT.md)
